pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('api-gateway') {
                    sh 'mvn clean package'
                }
            }
        }
    }
}
