pipeline {
    agent any

    tools {
        jdk 'JDK21'
        maven 'Maven'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('api-gateway') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('api-gateway') {
                    sh 'docker build -t api-gateway .'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                docker stop api-gateway || true
                docker rm api-gateway || true

                docker run -d \
                --name api-gateway \
                -p 8081:8080 \
                api-gateway
                '''
            }
        }
    }
}
