services:
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8081:8080"
    depends_on:
      - discovery-server
  account-service:
    build: ./account-service
    container_name: account-service
    depends_on:
      - discovery-server
  payment-service:
    build: ./payment-service
    container_name: payment-service
    depends_on:
      - discovery-server
  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    depends_on:
      - discovery-server
