server:
  port: 8084

spring:
  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:mysql://localhost:3306/ams
    username: root
    password: sysadmin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
